/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/incidents` | `/incidents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/incidents/new` | `/incidents/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/residents` | `/residents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/storeroom` | `/storeroom`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/storeroom/movement` | `/storeroom/movement`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/change-password` | `/change-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/residents/[id]` | `/residents/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/incidents` | `/incidents`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/incidents/new` | `/incidents/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/residents` | `/residents`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/storeroom` | `/storeroom`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/storeroom/movement` | `/storeroom/movement`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/change-password` | `/change-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/residents/[id]` | `/residents/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/incidents${`?${string}` | `#${string}` | ''}` | `/incidents${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/incidents/new${`?${string}` | `#${string}` | ''}` | `/incidents/new${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/residents${`?${string}` | `#${string}` | ''}` | `/residents${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/storeroom${`?${string}` | `#${string}` | ''}` | `/storeroom${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/storeroom/movement${`?${string}` | `#${string}` | ''}` | `/storeroom/movement${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/change-password${`?${string}` | `#${string}` | ''}` | `/change-password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/incidents` | `/incidents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/incidents/new` | `/incidents/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/residents` | `/residents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/storeroom` | `/storeroom`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/storeroom/movement` | `/storeroom/movement`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/change-password` | `/change-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | `${'/(app)'}/residents/${Router.SingleRoutePart<T>}` | `/residents/${Router.SingleRoutePart<T>}` | { pathname: `${'/(app)'}/residents/[id]` | `/residents/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
