packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
nodeLinker: hoisted
overrides:
  react-server-dom-webpack: 19.0.2
allowBuilds:
  '@nestjs/core': true
  '@sentry/cli': true
  '@sentry/node-cpu-profiler': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  puppeteer: true
  sharp: true
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@sentry/cli"
  - "@sentry/node-cpu-profiler"
  - bcrypt
  - esbuild
  - puppeteer
