packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  puppeteer: false
  sharp: true
onlyBuiltDependencies:
  - "@nestjs/core"
  - bcrypt
  - esbuild
