/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/checkin` | `/checkin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/wishlist` | `/wishlist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/messages/resident` | `/messages/resident`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/change-password` | `/change-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/messages/[staffId]` | `/messages/[staffId]`, params: Router.UnknownInputParams & { staffId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/checkin` | `/checkin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/wishlist` | `/wishlist`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/messages` | `/messages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/messages/resident` | `/messages/resident`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/change-password` | `/change-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/messages/[staffId]` | `/messages/[staffId]`, params: Router.UnknownOutputParams & { staffId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/checkin${`?${string}` | `#${string}` | ''}` | `/checkin${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/wishlist${`?${string}` | `#${string}` | ''}` | `/wishlist${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/messages${`?${string}` | `#${string}` | ''}` | `/messages${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/messages/resident${`?${string}` | `#${string}` | ''}` | `/messages/resident${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/change-password${`?${string}` | `#${string}` | ''}` | `/change-password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/checkin` | `/checkin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/wishlist` | `/wishlist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/messages/resident` | `/messages/resident`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/change-password` | `/change-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | `${'/(app)'}/messages/${Router.SingleRoutePart<T>}` | `/messages/${Router.SingleRoutePart<T>}` | { pathname: `${'/(app)'}/messages/[staffId]` | `/messages/[staffId]`, params: Router.UnknownInputParams & { staffId: string | number; } };
    }
  }
}
